name: Github - Deploy Package

on: [push]

jobs:
  deploy:
    name: deploy on github
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Deploy to Github Package Registry
      if: "contains(github.event.head_commit.message, 'Release')"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        chmod +x mvnw
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>OWNER</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        ./mvnw deploy
